### ISSUE TITLE
v3版本的SDK能否升级为2.0

### ISSUE THREAD

**Issue by season886** [overtrue/flysystem-cos#26]
V3.0.2版本的SDK为1.0不支持8.1的版本！
TP6他的league/flysystem只能1.0，所以没办法只能用V3.0.2版本。谢谢
```
During inheritance of ArrayAccess: Uncaught think\exception\ErrorException: Return type of Overtrue\CosClient\Config::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/tiger/vendor/overtrue/qcloud-cos-client/src/Config.php:92
Stack trace:
#0 /var/www/html/tiger/vendor/overtrue/qcloud-cos-client/src/Config.php(9): think\initializer\Error->appError()
#1 /var/www/html/tiger/vendor/composer/ClassLoader.php(571): include('/var/www/html/t...')
#2 /var/www/html/tiger/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/html/tiger/vendor/overtrue/qcloud-cos-client/src/ObjectClient.php(23): Composer\Autoload\ClassLoader->loadClass()
#4 /var/www/html/tiger/vendor/overtrue/flysystem-cos/src/CosAdapter.php(352): Overtrue\CosClient\ObjectClient->__construct()
#5 /var/www/html/tiger/vendor/overtrue/flysystem-cos/src/CosAdapter.php(67): Overtrue\Flysystem\Cos\CosAdapter->getObjectClient()
#6 /var/www/html/tiger/vendor/overtrue/flysystem-cos/src/CosAdapter.php(93): Overtrue\Flysystem\Cos\CosAdapter->write()
#7 /var/www/html/tiger/vendor/league/flysystem/src/Filesystem.php(123): Overtrue\Flysystem\Cos\CosAdapter->writeStream()
#8 /var/www/html/tiger/vendor/topthink/framework/src/think/filesystem/Driver.php(142): League\Flysystem\Filesystem->putStream()
#9 /var/www/html/tiger/vendor/topthink/framework/src/think/filesystem/Driver.php(131): think\filesystem\Driver->__call()
#10 /var/www/html/tiger/app/controller/Index.php(14): think\filesystem\Driver->putFileAs()
#11 [internal function]: app\controller\Index->index()
#12 /var/www/html/tiger/vendor/topthink/framework/src/think/Container.php(344): ReflectionMethod->invokeArgs()
#13 /var/www/html/tiger/vendor/topthink/framework/src/think/route/dispatch/Controller.php(110): think\Container->invokeReflectMethod()
#14 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(59): think\route\dispatch\Controller->think\route\dispatch\{closure}()
#15 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#16 /var/www/html/tiger/vendor/topthink/framework/src/think/route/dispatch/Controller.php(113): think\Pipeline->then()
#17 /var/www/html/tiger/vendor/topthink/framework/src/think/route/Dispatch.php(90): think\route\dispatch\Controller->exec()
#18 /var/www/html/tiger/vendor/topthink/framework/src/think/Route.php(785): think\route\Dispatch->run()
#19 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(59): think\Route->think\{closure}()
#20 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#21 /var/www/html/tiger/vendor/topthink/framework/src/think/Route.php(786): think\Pipeline->then()
#22 /var/www/html/tiger/vendor/topthink/framework/src/think/Http.php(216): think\Route->dispatch()
#23 /var/www/html/tiger/vendor/topthink/framework/src/think/Http.php(206): think\Http->dispatchToRoute()
#24 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(59): think\Http->think\{closure}()
#25 /var/www/html/tiger/vendor/topthink/think-trace/src/TraceDebug.php(71): think\Pipeline->think\{closure}()
#26 [internal function]: think\trace\TraceDebug->handle()
#27 /var/www/html/tiger/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#28 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#29 /var/www/html/tiger/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#30 /var/www/html/tiger/vendor/topthink/framework/src/think/Http.php(207): think\Pipeline->then()
#31 /var/www/html/tiger/vendor/topthink/framework/src/think/Http.php(170): think\Http->runWithRequest()
#32 /var/www/html/tiger/public/index.php(20): think\Http->run()
#33 {main}
```

**Comment by overtrue** [comment]
什么叫做 V3 能否升级2.0？降级？看不懂

season886 ***@***.***>于2022年8月12日 周五16:54写道：

**Comment by season886** [comment]
不好意思，没表达清楚
V3.0.2版本需要引用qcloud-cos-client这个SDK包，但是引用的是 "overtrue/qcloud-cos-client": "^1.0.0"，这个包在8.1会报上面的错，我看overtrue/qcloud-cos-client 2.0 已经修复了，看下能否把V3.0.2里面的composer.json里的"overtrue/qcloud-cos-client" 给升级成2.0

**Comment by season886** [comment]
我把V3.0.2的适配器给复制到我本地，然后单独安装了 "overtrue/qcloud-cos-client": "^2.0.0" ，目前可以运行了~
这里把qcloud-cos-client升级到2.0，应该会影响到8.0及以下版本的运行，因为ArrayAccess接口的方法签名不一样了，我也很期待与好奇作者如何处理这种兼容性问题？

**Comment by overtrue** [comment]
等我看看

season886 ***@***.***>于2022年8月14日 周日08:52写道：
